Repository ironcore-dev/dpservice-go, pull requests merged in 2023-12, with the labels that each got.

#49 Make project REUSE compliant
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  api/conversion.go
  api/types.go
  client/client.go
  errors/errors.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/generate-proto.sh
  hack/tools.go
Labels: enhancement, size/L

#50 Add `CODEOWNERS` to project
  .github/release-drafter.yml
  CODEOWNERS
Labels: size/XS

#54 Remove unused VirtualFunction fields
  api/types.go
  client/client.go
Labels: enhancement, size/S
